{% set version = "0.7.0" %}
{% set hash = "ff3dc9622c2406b7b583a283fbea651e" %}

package:
  name: pep257
  version: {{ version }}

source:
  fn: pep257-{{version}}.tar.gz
  url: https://pypi.io/packages/source/p/pep257/pep257-{{ version }}.tar.gz 
  md5: {{ hash }}

build:
    script: python setup.py install --single-version-externally-managed --record=record.txt
    number: 1001

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pep257

about:
  home: https://github.com/GreenSteam/pep257
  license: MIT
  license_file: LICENSE-MIT
  summary: 'Python docstring style checker (replaced by pydocstyle)'
  description: |
    pep257 is a static analysis tool for checking compliance with Python
    PEP 257.
    The framework for checking docstring style is flexible, and custom checks
    can be easily added, for example to cover NumPy docstring conventions.
    pep257 supports Python 2.6, 2.7, 3.2, 3.3, 3.4, pypy and pypy3.
  doc_url: http://pep257.readthedocs.io/en/latest
  dev_url: http://github.com/GreenSteam/pep257

extra:
  recipe-maintainers:
    - goanpeca
    - jakirkham
